# Generated by Django 5.0.6 on 2024-06-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='restaurante',
        ),
    ]
